### ISSUE TITLE
STO Modification

### ISSUE THREAD

**Issue by josiahakinloye** [simple-restricted-token/simple-restricted-token#11]
Since these ERC 1404 is a form of security token for Investors and also helps in sharing profit, Equity, Dividends and Buy back rights.... Can it be used to measure the value of the decentralized app and increase the value of token as the value of the digital asset(DAPPS) increase?

**Comment by youfoundron** [comment]
Implementing ERC-1404 does not make a token a security token.

1404 is simply a standard for enforcing transfer restrictions.

The functionality you're describing (profit-sharing, dividends, etc) do not fall under the concerns of the standard.
